### PR TITLE
Content Protection

### PR DESCRIPTION
**Pull request by phongkhuu115**
@daomapsieucap I have finished merging 2 options into 1, can you take your time to look at it, thank you !!

### CODE REVIEW

**Comment by daomapsieucap** [comment]
@zrvincent Could you help to update the code to prevent copy content from our previous project for the option Content Protection?

**Comment by zrvincent** [comment]
@daomapsieucap I updated code with above commit, please check PR.

**Comment by daomapsieucap** [comment]
@zrvincent Could you push your un-minified `fiber-content.js` please?

**Review by daomapsieucap — APPROVED** [review]
I think it looks good now. Thanks, @phongkhuu115 & @zrvincent for the contribution.

**Pull request merged**
